# CI Workflow Configuration
# This workflow runs tests on push and pull request events and updates the failing tests log if failures are detected.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        # This command runs tests and generates the junit.xml report
        run: npm test -- --ci --reporter=verbose

      - name: Update Failing Tests Log
        # If tests fail, this step can trigger a custom script to update the FAILING_TESTS_LOG.md
        run: |
          if [ -f coverage/junit.xml ]; then
            echo "Updating FAILING_TESTS_LOG.md from junit.xml..."
            npm run update-failing-tests
          fi
        shell: bash